export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:$PATH"
export PATH="/usr/local/mysql/bin:$PATH"
export PATH="/usr/local/share/npm/bin:$PATH"
export PATH="/Applications/VirtualBox.app/Contents/MacOS/:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"