# cask_args appdir: '~/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'caskroom/versions'
tap 'domt4/autoupdate'
tap 'phinze/cask'
# tap' mas-cli/tap'

brew 'ack'
brew 'autoconf'
brew 'autojump'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'coreutils'
brew 'curl'
brew 'dark-mode'
brew 'diff-so-fancy'
brew 'dnscrypt-proxy', restart_service: true
brew 'dockutil'
brew 'findutils'
brew 'fish'
brew 'gist'
brew 'git'
brew 'git-crypt'
brew 'git-flow'
brew 'git-lfs'
brew 'git-quick-stats'
brew 'git-secrets'
brew 'gitmoji'
brew 'gnupg'
brew 'go'
brew 'grep'
brew 'htop'
brew 'hub'
brew 'imagemagick'
# brew 'java'
brew 'jupyter'
brew 'libksba'
brew 'librsvg'
brew 'mas'
brew 'nano'
brew 'neovim'
brew 'ngrep'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'pigz'
brew 'pkg-config'
brew 'python'
brew 'python@2'
brew 'rbenv-default-gems'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'rename'
brew 'rhino'
brew 'rsync'
brew 'ruby'
brew 'smimesign'
brew 'speedtest-cli'
brew 'stubby'
brew 'terminal-notifier'
brew 'thefuck'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'webkit2png'
brew 'wget'
brew 'wifi-password'
brew 'yarn', args: ["ignore-dependencies"]
brew 'zopfli'

cask '1password'
cask 'abstract'
cask 'atom'
cask 'bartender'
cask 'diffmerge'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'iina'
cask 'istat-menus'
cask 'iterm2'
cask 'itsycal'
cask 'keka'
cask 'kitty'
cask 'ksdiff'
cask 'micro-snitch'
cask 'postman'
cask 'rocket'
cask 'sketch'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'spotify-notifications'
cask 'tower'
cask 'transmission'
cask 'tripmode'
cask 'visual-studio-code'
cask 'zeplin'
cask 'zoomus'

# software for home computers.
# cask 'avast-security'
# cask 'battle-net'
# cask 'filebot'
# cask 'plex-media-server'
# cask 'steam'

# fonts.
cask 'font-fira-code'
cask 'font-open-sans'
cask 'font-roboto-mono'
cask 'font-source-code-pro'

# quicklook.
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-json'
cask 'quicklookase'
cask 'suspicious-package'
cask 'webpquicklook'

# app store.
mas 'Clear', id: 504544917
mas 'Fantastical', id: 975937182
mas 'iA Writer', id: 775737590
mas 'Kaleidoscope', id: 587512244
mas 'Markoff', id: 1084713122
mas 'NordVPN IKE', id: 1116599239
mas 'Tweetbot', id: 557168941
