# cask_args appdir: '~/Applications'

tap 'homebrew/bundle'
# tap 'homebrew/cask'
# tap 'homebrew/core'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
# tap 'homebrew/versions'
tap 'buo/cask-upgrade'
# tap' mas-cli/tap'

brew 'ack'
brew 'autoconf'
brew 'autojump'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'cmake'
brew 'coreutils'
brew 'curl'
brew 'dark-mode'
brew 'dnscrypt-proxy', restart_service: true
brew 'dockutil'
brew 'findutils'
brew 'fish'
brew 'gist'
brew 'git'
brew 'git-crypt'
brew 'git-delta'
brew 'git-flow'
brew 'git-lfs'
brew 'git-quick-stats'
brew 'git-secrets'
brew 'gitmoji'
brew 'gnupg'
# brew 'go'
brew 'gpg2'
brew 'grep'
brew 'htop'
brew 'hub'
brew 'imagemagick'
# brew 'java'
brew 'libksba'
brew 'librsvg'
brew 'homebrew/core/make'
brew 'mas'
brew 'nano'
brew 'neovim'
brew 'ngrep'
brew 'ninja'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'pigz'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'python'
brew 'pyenv'
brew 'rbenv-default-gems'
brew 'rbenv'
brew 'rename'
brew 'rhino'
brew 'rsync'
brew 'ruby'
brew 'smimesign'
brew 'speedtest-cli'
brew 'stubby'
brew 'swift'
brew 'terminal-notifier'
brew 'thefuck'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'watchman'
brew 'webkit2png'
brew 'wget'
brew 'wifi-password'
brew 'yarn', args: ["ignore-dependencies"]
brew 'zopfli'

# artpro.
# tap 'weaveworks/tap'
# brew 'kubernetes-cli'
# brew 'weaveworks/tap/eksctls'

cask '1password'
cask 'abstract'
cask 'atom'
cask 'bartender'
cask 'diffmerge'
cask 'discord'
cask 'figma'
cask 'firefox'
cask 'gpg-suite'
cask 'google-chrome'
cask 'google-drive'
cask 'iina'
# cask 'istat-menus'
cask 'iterm2'
cask 'itsycal'
cask 'keka'
cask 'kitty'
cask 'ksdiff'
cask 'logitech-options'
cask 'micro-snitch'
cask 'microsoft-edge'
cask 'postman'
cask 'rocket'
cask 'slack'
cask 'spectacle'
# cask 'spotify'
cask 'tower'
cask 'tripmode'
cask 'visual-studio-code'
# cask 'zeplin'
cask 'zoom'

# fonts.
cask 'font-fira-code'
cask 'font-open-sans'
cask 'font-roboto-mono'
cask 'font-source-code-pro'

# quicklook.
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlvideo'
cask 'quicklook-json'
cask 'quicklookase'
cask 'suspicious-package'
cask 'webpquicklook'

# app store.
mas 'CARROT Weather', id: 993487541
# mas 'Clear', id: 504544917
mas 'Fantastical', id: 975937182
mas 'iA Writer', id: 775737590
mas 'Kaleidoscope', id: 587512244
mas 'NordVPN', id: 905953485
mas 'Pixelmator Pro', id: 1289583905
# mas 'Tweetbot', id: 557168941

# software for home computers.
# cask 'battle-net'
# cask 'macs-fan-control'
# cask 'plex'
# cask 'plex-media-server'
# cask 'steam'
# cask 'transmission'
# mas 'AutoMounter', id: 1160435653
# mas 'Encrypto', id: 935235287
# mas 'Filebot', id: 905384638
